// AUTO-GENERATED — tek doğruluk kaynağı: backend/app/core/team_translations.py
// (NATIONAL_TEAMS_TR + CLUBS_TR anahtar ve değerleri). Backend listesi değişirse
// bu dosya da yeniden üretilmeli. Yeni liste/regex UYDURULMAZ.
const RAW: string[] = [
  "ABD",
  "AC Milan",
  "AS Roma",
  "Adana Demirspor",
  "Afganistan",
  "Afghanistan",
  "Ajax",
  "Alanyaspor",
  "Albania",
  "Algeria",
  "Almanya",
  "Andorra",
  "Angola",
  "Antalyaspor",
  "Argentina",
  "Arjantin",
  "Armenia",
  "Arnavutluk",
  "Arsenal",
  "Aston Villa",
  "Atalanta",
  "Athletic Bilbao",
  "Athletic Club",
  "Atletico Madrid",
  "Atlético Madrid",
  "Australia",
  "Austria",
  "Avustralya",
  "Avusturya",
  "Azerbaijan",
  "Azerbaycan",
  "BAE",
  "Bahrain",
  "Bahreyn",
  "Bangladesh",
  "Bangladeş",
  "Barcelona",
  "Bayer Leverkusen",
  "Bayern",
  "Bayern Munich",
  "Bayern München",
  "Bayern Münih",
  "Belarus",
  "Belgium",
  "Belçika",
  "Benfica",
  "Besiktas",
  "Beşiktaş",
  "Birleşik Arap Emirlikleri",
  "Bodrum",
  "Bodrum FK",
  "Bolivia",
  "Bolivya",
  "Bologna",
  "Borussia Dortmund",
  "Bosna Hersek",
  "Bosnia & Herzegovina",
  "Bosnia and Herzegovina",
  "Brazil",
  "Brezilya",
  "Bulgaria",
  "Bulgaristan",
  "Burkina Faso",
  "Cameroon",
  "Canada",
  "Cape Verde",
  "Cebelitarık",
  "Celtic",
  "Cezayir",
  "Chelsea",
  "Chile",
  "China",
  "China PR",
  "Colombia",
  "Comoros",
  "Congo",
  "Costa Rica",
  "Croatia",
  "Cuba",
  "Curacao",
  "Curaçao",
  "Cyprus",
  "Czech Republic",
  "Czechia",
  "Côte d'Ivoire",
  "DR Congo",
  "Danimarka",
  "Democratic Republic of Congo",
  "Demokratik Kongo Cumhuriyeti",
  "Denmark",
  "Dortmund",
  "Ecuador",
  "Egypt",
  "Eintracht Frankfurt",
  "Ekvador",
  "Ekvator Ginesi",
  "El Salvador",
  "Endonezya",
  "England",
  "Equatorial Guinea",
  "Ermenistan",
  "Estonia",
  "Estonya",
  "Ethiopia",
  "Etiyopya",
  "Eyupspor",
  "Eyüpspor",
  "FC Porto",
  "Faroe Adaları",
  "Faroe Islands",
  "Fas",
  "Fenerbahce",
  "Fenerbahçe",
  "Feyenoord",
  "Fiji",
  "Fildişi Sahili",
  "Filipinler",
  "Filistin",
  "Finland",
  "Finlandiya",
  "Fiorentina",
  "France",
  "Fransa",
  "Gabon",
  "Galatasaray",
  "Galler",
  "Gana",
  "Gaziantep",
  "Gaziantep FK",
  "Georgia",
  "Germany",
  "Ghana",
  "Gibraltar",
  "Gine",
  "Goztepe",
  "Greece",
  "Guatemala",
  "Guinea",
  "Göztepe",
  "Güney Afrika",
  "Güney Kore",
  "Gürcistan",
  "Haiti",
  "Hatayspor",
  "Hindistan",
  "Hollanda",
  "Honduras",
  "Hungary",
  "Hırvatistan",
  "Iceland",
  "India",
  "Indonesia",
  "Inter",
  "Inter Milan",
  "Irak",
  "Iran",
  "Iraq",
  "Ireland",
  "Israel",
  "Istanbul Basaksehir",
  "Italy",
  "Ivory Coast",
  "Jamaica",
  "Jamaika",
  "Japan",
  "Japonya",
  "Jordan",
  "Juventus",
  "Kamerun",
  "Kanada",
  "Karadağ",
  "Kasimpasa",
  "Kasımpaşa",
  "Katar",
  "Kayserispor",
  "Kazakhstan",
  "Kazakistan",
  "Kenya",
  "Kolombiya",
  "Komorlar",
  "Kongo",
  "Konyaspor",
  "Korea DPR",
  "Korea Republic",
  "Kosova",
  "Kosovo",
  "Kosta Rika",
  "Kuveyt",
  "Kuwait",
  "Kuzey Kore",
  "Kuzey Makedonya",
  "Kuzey İrlanda",
  "Kyrgyzstan",
  "Küba",
  "Kıbrıs",
  "Kırgızistan",
  "Latvia",
  "Lazio",
  "Lebanon",
  "Letonya",
  "Leverkusen",
  "Libya",
  "Liechtenstein",
  "Lihtenştayn",
  "Lille",
  "Lithuania",
  "Litvanya",
  "Liverpool",
  "Luxembourg",
  "Lyon",
  "Lübnan",
  "Lüksemburg",
  "Macaristan",
  "Madagascar",
  "Madagaskar",
  "Malaysia",
  "Malezya",
  "Mali",
  "Malta",
  "Manchester City",
  "Manchester United",
  "Marseille",
  "Marsilya",
  "Mauritania",
  "Meksika",
  "Mexico",
  "Milan",
  "Moldova",
  "Monaco",
  "Montenegro",
  "Moritanya",
  "Morocco",
  "Mozambik",
  "Mozambique",
  "Mısır",
  "Napoli",
  "Netherlands",
  "New Zealand",
  "Newcastle",
  "Newcastle United",
  "Nice",
  "Nigeria",
  "Nijerya",
  "North Korea",
  "North Macedonia",
  "Northern Ireland",
  "Norveç",
  "Norway",
  "Oman",
  "PSG",
  "PSV",
  "PSV Eindhoven",
  "Pakistan",
  "Palestine",
  "Panama",
  "Papua New Guinea",
  "Papua Yeni Gine",
  "Paraguay",
  "Paris Saint-Germain",
  "Peru",
  "Philippines",
  "Poland",
  "Polonya",
  "Portekiz",
  "Porto",
  "Portugal",
  "Qatar",
  "RB Leipzig",
  "Rangers",
  "Real Betis",
  "Real Madrid",
  "Real Sociedad",
  "Rennes",
  "Rizespor",
  "Roma",
  "Romania",
  "Romanya",
  "Russia",
  "Rusya",
  "Samsunspor",
  "San Marino",
  "Saudi Arabia",
  "Scotland",
  "Senegal",
  "Serbia",
  "Sevilla",
  "Singapore",
  "Singapur",
  "Sivasspor",
  "Slovakia",
  "Slovakya",
  "Slovenia",
  "Slovenya",
  "Solomon Adaları",
  "Solomon Islands",
  "South Africa",
  "South Korea",
  "Spain",
  "Sporting",
  "Sporting CP",
  "Stuttgart",
  "Sudan",
  "Suriye",
  "Suudi Arabistan",
  "Sweden",
  "Switzerland",
  "Syria",
  "Sırbistan",
  "Tacikistan",
  "Tahiti",
  "Tajikistan",
  "Tanzania",
  "Tanzanya",
  "Tayland",
  "Thailand",
  "Tottenham",
  "Tottenham Hotspur",
  "Trabzonspor",
  "Trinidad and Tobago",
  "Trinidad ve Tobago",
  "Tunisia",
  "Tunus",
  "Turkey",
  "Turkiye",
  "Turkmenistan",
  "Türkiye",
  "Türkmenistan",
  "UAE",
  "USA",
  "Uganda",
  "Ukraine",
  "Ukrayna",
  "Umman",
  "United Arab Emirates",
  "United States",
  "Uruguay",
  "Uzbekistan",
  "Valencia",
  "Venezuela",
  "Vietnam",
  "Villarreal",
  "Wales",
  "Yemen",
  "Yeni Zelanda",
  "Yeşil Burun",
  "Yunanistan",
  "Zambia",
  "Zambiya",
  "Zimbabve",
  "Zimbabwe",
  "Çaykur Rizespor",
  "Çek Cumhuriyeti",
  "Çekya",
  "Çin",
  "Özbekistan",
  "Ürdün",
  "İngiltere",
  "İran",
  "İrlanda",
  "İskoçya",
  "İspanya",
  "İsrail",
  "İstanbul Başakşehir",
  "İsveç",
  "İsviçre",
  "İtalya",
  "İzlanda",
  "Şili"
];

const norm = (s: string) =>
  (s || '')
    .replace(/İ/g, 'i')
    .toLowerCase()
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .replace(/ı/g, 'i').replace(/ş/g, 's').replace(/ğ/g, 'g')
    .replace(/ü/g, 'u').replace(/ö/g, 'o').replace(/ç/g, 'c')
    .trim();

const KNOWN = new Set(RAW.map(norm));

export const isKnownTeam = (name: string): boolean => KNOWN.has(norm(name));
